In [1]:
from agentflow.buffers.segment_tree import SumTree
import agentflow.buffers.segment_tree_c as segment_tree
from agentflow.common.sum_prefix_tree import SumPrefixTree
import numpy as np

## Construct tree objects

In [2]:
n = int(2000)

x = (np.random.choice(50,size=n)+1).astype(float)
idx = np.arange(n).astype(np.int32)

sumtree2 = np.zeros(n*2)
sumtree3 = SumPrefixTree(np.zeros(n).copy())

## Set all values

In [3]:
x = (np.random.choice(50,size=n)+1).astype(float)
idx = np.arange(n).astype(np.int32)

In [4]:
x

array([13., 11., 14., ...,  6., 38.,  2.])

In [5]:
x.shape

(2000,)

In [6]:
segment_tree.update_tree_multi(idx,x,sumtree2)

In [7]:
sumtree3[idx] = x

In [8]:
np.abs(sumtree3 - sumtree2[n:]).max()

0.0

In [9]:
np.abs(sumtree3._sumtree - sumtree2[:n]).max()

0.0

## multiple get prefix sum id

In [10]:
x.sum()

51508.0

In [16]:
y = np.random.rand(1000)*x.sum()

In [17]:
out2 = np.zeros(y.shape,dtype=np.int32)

In [18]:
segment_tree.get_prefix_sum_multi_idx(out2,y,sumtree2)

array([1706,  896, 1434,   89,  249, 1264,  196, 1076,  897, 1353,  689,
        236,  701,  543, 1470,  961, 1487, 1029, 1105,  868, 1125,  266,
       1559,  564, 1930, 1910,    1, 1724, 1238, 1316, 1902,  750,  231,
        295, 1499, 1427, 1724, 1803, 1791, 1374, 1001,  199, 1127, 1182,
        997, 1100,  252,  385,  189, 1798,  227, 1728,  530,   66,  106,
        178,  288, 1678, 1027, 1094,  952,  769,  558, 1470,  764, 1007,
        723, 1092, 1269, 1336,  471, 1444, 1683,  788, 1637,  557, 1253,
        448, 1970, 1973,  213, 1570, 1716, 1507, 1840, 1518,  680,  753,
       1659,  640, 1436, 1822,  889,  849, 1574,  633, 1829, 1410,  450,
       1789,  333, 1187, 1614, 1801,  759,  685,  532,  523,  635,  443,
        602, 1226, 1988, 1172, 1977, 1710, 1480, 1181,  935, 1132, 1338,
       1129, 1705, 1427,  946,  881, 1043, 1822,  346,  704,   31, 1266,
       1534, 1550,  162,  112, 1022,   53, 1519, 1217,  887,  942, 1819,
       1442, 1059, 1494, 1691, 1318,  456,  821,  6

In [19]:
out3 = sumtree3.get_prefix_sum_id(y)
out3

array([1706,  896, 1434,   89,  249, 1264,  196, 1076,  897, 1353,  689,
        236,  701,  543, 1470,  961, 1487, 1029, 1105,  868, 1125,  266,
       1559,  564, 1930, 1910,    1, 1724, 1238, 1316, 1902,  750,  231,
        295, 1499, 1427, 1724, 1803, 1791, 1374, 1001,  199, 1127, 1182,
        997, 1100,  252,  385,  189, 1798,  227, 1728,  530,   66,  106,
        178,  288, 1678, 1027, 1094,  952,  769,  558, 1470,  764, 1007,
        723, 1092, 1269, 1336,  471, 1444, 1683,  788, 1637,  557, 1253,
        448, 1970, 1973,  213, 1570, 1716, 1507, 1840, 1518,  680,  753,
       1659,  640, 1436, 1822,  889,  849, 1574,  633, 1829, 1410,  450,
       1789,  333, 1187, 1614, 1801,  759,  685,  532,  523,  635,  443,
        602, 1226, 1988, 1172, 1977, 1710, 1480, 1181,  935, 1132, 1338,
       1129, 1705, 1427,  946,  881, 1043, 1822,  346,  704,   31, 1266,
       1534, 1550,  162,  112, 1022,   53, 1519, 1217,  887,  942, 1819,
       1442, 1059, 1494, 1691, 1318,  456,  821,  6

In [15]:
np.abs(out2-out3).max()

0