In [1]:
import gym
import numpy as np

In [2]:
env = gym.make('Pendulum-v0')

In [3]:
ob = env.reset()
ob

array([-0.94852834,  0.31669227,  0.46602759])

In [4]:
#env.render()

In [5]:
env.action_space.sample()

array([-0.19794883], dtype=float32)

In [6]:
env.action_space.low, env.action_space.high

(array([-2.], dtype=float32), array([2.], dtype=float32))

In [11]:
for i in range(100):
    ob, reward, done, info = env.step(np.array([2]))
    print(reward)

-4.880225034926382
-5.4875889825940645
-6.185666004722163
-6.95383942188149
-7.7644576223598305
-8.584657714158599
-9.379565161669248
-10.116026772552807
-10.21498897862566
-9.407501457280455
-8.736286830992876
-8.23262826265731
-7.921174325471338
-7.8183967135562575
-7.931743921801156
-8.25914020979815
-8.788630406612716
-9.498315309254986
-10.35702220439431
-9.771707575362543
-9.063942039963235
-8.314594968094994
-7.548228345154998
-6.791647510076394
-6.071688432366198
-5.4126648043528505
-4.834329373238942
-4.350934901499242
-3.971486520086408
-3.7008637723168483
-3.5413142058944134
-3.493854925965866
-3.559253102784715
-3.7383961919843625
-4.031970427960427
-4.439455246112987
-4.957548587839216
-5.578293004552788
-6.287364169947984
-7.063133909617502
-7.877092179604705
-8.695888095263582
-9.484663724214904
-10.21077297792676
-10.097525581520975
-9.306681699409431
-8.656711038806861
-8.178111013119823
-7.894481675167331
-7.821096600642244
-7.964124415528646
-8.320152899539107
-8.875